"""jobs, results and feedback

Revision ID: 0001
Revises:
Create Date: 2026-08-26

Hand-written rather than autogenerated: autogenerate needs a live database to diff
against, and a migration that only exists where someone happened to have Postgres
running is not a migration anyone else can trust.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_JSONB = postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite")
_UUID = postgresql.UUID(as_uuid=True).with_variant(sa.String(36), "sqlite")


def upgrade() -> None:
    op.create_table(
        "jobs",
        sa.Column("id", _UUID, primary_key=True),
        sa.Column("correlation_id", sa.String(64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                name="job_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("filename", sa.String(255), nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(8), nullable=False, server_default="en"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("report", _JSONB, nullable=True),
        sa.Column("graph_version", sa.String(64), nullable=True),
        sa.Column("corpus_version", sa.String(64), nullable=True),
    )
    op.create_index("ix_jobs_correlation_id", "jobs", ["correlation_id"])
    op.create_index("ix_jobs_sha256", "jobs", ["sha256"])
    op.create_index("ix_jobs_status_created", "jobs", ["status", "created_at"])

    op.create_table(
        "results",
        sa.Column("id", _UUID, primary_key=True),
        sa.Column("job_id", _UUID, sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("rule_id", sa.String(64), nullable=False),
        sa.Column("verdict", sa.String(16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("abstention_reason", sa.String(64), nullable=True),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("citations", _JSONB, nullable=True),
        sa.Column("metrics", _JSONB, nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=False, server_default="0"),
        sa.Column("duration_ms", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index("ix_results_job_id", "results", ["job_id"])
    op.create_index("ix_results_rule_id", "results", ["rule_id"])
    op.create_index("ix_results_verdict", "results", ["verdict"])

    op.create_table(
        "feedback",
        sa.Column("id", _UUID, primary_key=True),
        sa.Column("job_id", _UUID, sa.ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("rule_id", sa.String(64), nullable=False),
        sa.Column("corrected_verdict", sa.String(16), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("reviewer", sa.String(128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_feedback_job_id", "feedback", ["job_id"])
    op.create_index("ix_feedback_rule_id", "feedback", ["rule_id"])


def downgrade() -> None:
    op.drop_table("feedback")
    op.drop_table("results")
    op.drop_table("jobs")
